import type { Metadata } from 'next';
import { fetchReport } from '@/lib/share-store';
import { CritiqueReportView } from '@/components/critique/CritiqueReport';

export const metadata: Metadata = {
  title: 'UX Critique Report — CritiqueAI',
  description: 'A structured UX critique generated by CritiqueAI, powered by Gemini.',
};

interface PageProps {
  params: { id: string };
}

export default async function ReportPage({ params }: PageProps) {
  const stored = await fetchReport(params.id);

  if (!stored) {
    return (
      <main className="min-h-screen flex items-center justify-center">
        <div className="text-center max-w-[400px] px-6">
          <h1 className="text-h2 mb-2">Report not found</h1>
          <p className="text-[14px] text-[#57534E]">
            This report may have expired or the link may be incorrect.
          </p>
          <a
            href="/"
            className="inline-block mt-4 text-[#4338CA] text-[14px] underline hover:no-underline"
          >
            Run a new critique
          </a>
        </div>
      </main>
    );
  }

  // The stored image is hosted on Supabase Storage — we'll re-fetch as base64
  // For simplicity we pass the image URL and display it directly via an img tag
  // The CritiqueReportView accepts either base64 or a URL prefix
  const res = await fetch(stored.image_url);
  const arrayBuffer = await res.arrayBuffer();
  const base64 = Buffer.from(arrayBuffer).toString('base64');
  const mimeType = res.headers.get('content-type') ?? 'image/png';

  return (
    <main className="min-h-screen">
      <header className="border-b border-[#E7E5E4] bg-white h-[60px] flex items-center">
        <div className="w-full px-4 md:px-8 flex items-center justify-between">
          <a href="/" className="flex items-center gap-2 cursor-pointer" aria-label="CritiqueAI home">
            <div className="w-7 h-7 rounded-md bg-[#4338CA] flex items-center justify-center shrink-0" aria-hidden="true">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="11" cy="11" r="8" />
                <line x1="21" y1="21" x2="16.65" y2="16.65" />
              </svg>
            </div>
            <span className="text-[15px] font-semibold text-[#1C1917] tracking-tight">CritiqueAI</span>
          </a>
          <a
            href="/"
            className="text-[13px] text-[#4338CA] hover:text-[#3730A3] transition-colors cursor-pointer"
          >
            Run your own critique →
          </a>
        </div>
      </header>

      <div className="content-container py-10">
        <p className="text-[12px] text-[#A8A29E] font-mono mb-6">
          Shared report · {new Date(stored.created_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>
        <CritiqueReportView
          report={stored.report}
          imageBase64={base64}
          mimeType={mimeType}
        />
      </div>
    </main>
  );
}
