/**
 * lib/markdown-export.ts — Serializes a CritiqueReport to Markdown.
 * Pure function, no side effects.
 */

import type { CritiqueReport, CritiqueIssue, Severity } from '@/types/critique';

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴 Critical',
  major: '🟠 Major',
  minor: '🟡 Minor',
  suggestion: '🟢 Suggestion',
};

function formatIssue(issue: CritiqueIssue, index: number): string {
  return `### ${index + 1}. ${issue.title}

**Severity**: ${SEVERITY_EMOJI[issue.severity]}  
**Category**: ${issue.category}  
**Heuristic / Criterion**: \`${issue.heuristic}\`  
**Location**: ${issue.location_hint}

**What**: ${issue.what}

**Why it matters**: ${issue.why}

**Fix**: ${issue.fix}
`;
}

export function reportToMarkdown(report: CritiqueReport): string {
  const modeLabels: Record<string, string> = {
    quick_scan: 'Quick Scan',
    full_audit: 'Full Audit',
    accessibility_only: 'Accessibility Only',
    mobile_ux: 'Mobile UX Check',
  };

  const lines: string[] = [
    `# UX Critique Report`,
    ``,
    `**Mode**: ${modeLabels[report.mode] ?? report.mode}  `,
    `**Overall Score**: ${report.overall_score}/100`,
    ``,
    `## Summary`,
    ``,
    report.summary,
    ``,
    `## Issues (${report.issues.length})`,
    ``,
    ...report.issues.map((issue, i) => formatIssue(issue, i)),
  ];

  if (report.strengths.length > 0) {
    lines.push(`## Strengths`, ``);
    report.strengths.forEach((s) => lines.push(`- ${s}`));
    lines.push(``);
  }

  lines.push(
    `## Priority Fix`,
    ``,
    report.priority_fix,
    ``,
    `---`,
    ``,
    `*Generated by [CritiqueAI](${process.env.NEXT_PUBLIC_APP_URL ?? 'https://critiqueai.app'})*`,
  );

  return lines.join('\n');
}
